server:
    port: 8080
spring:
    datasource:
        driver-class-name: org.h2.Driver
        username: sa
        password: 123456
        url: jdbc:h2:file:./src/main/resources/rental;MODE=MYSQL;
    jpa:
        database: h2
        hibernate:
            ddl-auto: update
        show-sql: true
    h2:
        console:
            path: /h2-console
            enabled: true
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    sql:
        init:
            mode: always
